# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TarsStackchan < Formula
  desc "MCP bridge and local control UI for M5Stack Stack-chan"
  homepage "https://github.com/devlikebear/tars-stackchan"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/devlikebear/tars-stackchan/releases/download/v0.1.0/tars-stackchan_0.1.0_darwin_amd64.tar.gz"
      sha256 "e671f308ef5ff49d573d2ad1a8a7596696cbc4a70671294db874448d135af001"

      define_method(:install) do
        libexec.install "tars-stackchan-mcp"
        libexec.install "tars-stackchan-control"
        pkgshare.install "scripts"
        pkgshare.install "firmware"
        (bin/"tars-stackchan-mcp").write_env_script libexec/"tars-stackchan-mcp", TARS_STACKCHAN_REPO_ROOT: pkgshare
        (bin/"tars-stackchan-control").write_env_script libexec/"tars-stackchan-control", TARS_STACKCHAN_REPO_ROOT: pkgshare
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/devlikebear/tars-stackchan/releases/download/v0.1.0/tars-stackchan_0.1.0_darwin_arm64.tar.gz"
      sha256 "f20718cfdf532ff90e5dcde6e87763aaea83510a69b8362cc21df2280fa9f0c2"

      define_method(:install) do
        libexec.install "tars-stackchan-mcp"
        libexec.install "tars-stackchan-control"
        pkgshare.install "scripts"
        pkgshare.install "firmware"
        (bin/"tars-stackchan-mcp").write_env_script libexec/"tars-stackchan-mcp", TARS_STACKCHAN_REPO_ROOT: pkgshare
        (bin/"tars-stackchan-control").write_env_script libexec/"tars-stackchan-control", TARS_STACKCHAN_REPO_ROOT: pkgshare
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/devlikebear/tars-stackchan/releases/download/v0.1.0/tars-stackchan_0.1.0_linux_amd64.tar.gz"
      sha256 "56d92229c06b4ad4878042cca93dc2a66a8e059676f1128767ce97dff8d08f6b"
      define_method(:install) do
        libexec.install "tars-stackchan-mcp"
        libexec.install "tars-stackchan-control"
        pkgshare.install "scripts"
        pkgshare.install "firmware"
        (bin/"tars-stackchan-mcp").write_env_script libexec/"tars-stackchan-mcp", TARS_STACKCHAN_REPO_ROOT: pkgshare
        (bin/"tars-stackchan-control").write_env_script libexec/"tars-stackchan-control", TARS_STACKCHAN_REPO_ROOT: pkgshare
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/devlikebear/tars-stackchan/releases/download/v0.1.0/tars-stackchan_0.1.0_linux_arm64.tar.gz"
      sha256 "d352436f3da54c8d7359ffcf5de76094fccccaa350fb503ad35b6152715ea462"
      define_method(:install) do
        libexec.install "tars-stackchan-mcp"
        libexec.install "tars-stackchan-control"
        pkgshare.install "scripts"
        pkgshare.install "firmware"
        (bin/"tars-stackchan-mcp").write_env_script libexec/"tars-stackchan-mcp", TARS_STACKCHAN_REPO_ROOT: pkgshare
        (bin/"tars-stackchan-control").write_env_script libexec/"tars-stackchan-control", TARS_STACKCHAN_REPO_ROOT: pkgshare
      end
    end
  end

  def caveats
    <<~EOS
      Install and connect to Claude Code:
        export TARS_STACKCHAN_TOKEN="replace-with-local-token"
        tars-stackchan-mcp install --target claude-code --firmware-tools

      The stackchan_upload_firmware tool is hidden unless TARS_STACKCHAN_ENABLE_FIRMWARE_TOOLS=1 is set.
      Run tars-stackchan-mcp doctor before allowing an agent to flash hardware.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tars-stackchan-mcp --version")
    assert_match version.to_s, shell_output("#{bin}/tars-stackchan-control --version")
    assert_match "TARS_STACKCHAN_ENABLE_FIRMWARE_TOOLS=1", shell_output("#{bin}/tars-stackchan-mcp config --target claude-code --firmware-tools")
  end
end
