# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TarsStackchan < Formula
  desc "MCP bridge and local control UI for M5Stack Stack-chan"
  homepage "https://github.com/devlikebear/tars-stackchan"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/devlikebear/tars-stackchan/releases/download/v0.1.2/tars-stackchan_0.1.2_darwin_amd64.tar.gz"
      sha256 "90bb92d55e41e319dc89b25059234151f7c3407ea90ab16e4543bfda7bb987a5"

      define_method(:install) do
        libexec.install "tars-stackchan-mcp"
        libexec.install "tars-stackchan-control"
        pkgshare.install "scripts"
        pkgshare.install "firmware"
        (bin/"tars-stackchan-mcp").write_env_script libexec/"tars-stackchan-mcp", TARS_STACKCHAN_REPO_ROOT: pkgshare
        (bin/"tars-stackchan-control").write_env_script libexec/"tars-stackchan-control", TARS_STACKCHAN_REPO_ROOT: pkgshare
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/devlikebear/tars-stackchan/releases/download/v0.1.2/tars-stackchan_0.1.2_darwin_arm64.tar.gz"
      sha256 "a4352e6f08f3e886f77ca559d7dda4eee4df4232bf94feb8a1e3a71e1f08b031"

      define_method(:install) do
        libexec.install "tars-stackchan-mcp"
        libexec.install "tars-stackchan-control"
        pkgshare.install "scripts"
        pkgshare.install "firmware"
        (bin/"tars-stackchan-mcp").write_env_script libexec/"tars-stackchan-mcp", TARS_STACKCHAN_REPO_ROOT: pkgshare
        (bin/"tars-stackchan-control").write_env_script libexec/"tars-stackchan-control", TARS_STACKCHAN_REPO_ROOT: pkgshare
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/devlikebear/tars-stackchan/releases/download/v0.1.2/tars-stackchan_0.1.2_linux_amd64.tar.gz"
      sha256 "f05003bf17987b53640e4427ccb1d2ca5d5036f22e0a691d302b3bbcd2e26108"
      define_method(:install) do
        libexec.install "tars-stackchan-mcp"
        libexec.install "tars-stackchan-control"
        pkgshare.install "scripts"
        pkgshare.install "firmware"
        (bin/"tars-stackchan-mcp").write_env_script libexec/"tars-stackchan-mcp", TARS_STACKCHAN_REPO_ROOT: pkgshare
        (bin/"tars-stackchan-control").write_env_script libexec/"tars-stackchan-control", TARS_STACKCHAN_REPO_ROOT: pkgshare
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/devlikebear/tars-stackchan/releases/download/v0.1.2/tars-stackchan_0.1.2_linux_arm64.tar.gz"
      sha256 "3ba1fb66e27438abc66fc2a2c6375b8ea70a8ca03c8637f4d8ba18e77a7c6dad"
      define_method(:install) do
        libexec.install "tars-stackchan-mcp"
        libexec.install "tars-stackchan-control"
        pkgshare.install "scripts"
        pkgshare.install "firmware"
        (bin/"tars-stackchan-mcp").write_env_script libexec/"tars-stackchan-mcp", TARS_STACKCHAN_REPO_ROOT: pkgshare
        (bin/"tars-stackchan-control").write_env_script libexec/"tars-stackchan-control", TARS_STACKCHAN_REPO_ROOT: pkgshare
      end
    end
  end

  def caveats
    <<~EOS
      Install and connect to Claude Code:
        export TARS_STACKCHAN_TOKEN="replace-with-local-token"
        tars-stackchan-mcp install --target claude-code --firmware-tools

      The stackchan_upload_firmware tool is hidden unless TARS_STACKCHAN_ENABLE_FIRMWARE_TOOLS=1 is set.
      Run tars-stackchan-mcp doctor before allowing an agent to flash hardware.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tars-stackchan-mcp --version")
    assert_match version.to_s, shell_output("#{bin}/tars-stackchan-control --version")
    assert_match "TARS_STACKCHAN_ENABLE_FIRMWARE_TOOLS=1", shell_output("#{bin}/tars-stackchan-mcp config --target claude-code --firmware-tools")
  end
end
