# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TarsStackchan < Formula
  desc "MCP bridge and local control UI for M5Stack Stack-chan"
  homepage "https://github.com/devlikebear/tars-stackchan"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/devlikebear/tars-stackchan/releases/download/v0.2.0/tars-stackchan_0.2.0_darwin_amd64.tar.gz"
      sha256 "08c3ce9d3ad04739b559d4f1a9fdca0b072e841fa467df2b6f03a9696b99d480"

      define_method(:install) do
        libexec.install "tars-stackchan-mcp"
        libexec.install "tars-stackchan-control"
        pkgshare.install "scripts"
        pkgshare.install "firmware"
        (bin/"tars-stackchan-mcp").write_env_script libexec/"tars-stackchan-mcp", TARS_STACKCHAN_REPO_ROOT: pkgshare
        (bin/"tars-stackchan-control").write_env_script libexec/"tars-stackchan-control", TARS_STACKCHAN_REPO_ROOT: pkgshare
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/devlikebear/tars-stackchan/releases/download/v0.2.0/tars-stackchan_0.2.0_darwin_arm64.tar.gz"
      sha256 "7436e57aaeeb89a67c44fa03e6051a3f471fd4c136c75bad9d51292234d12e71"

      define_method(:install) do
        libexec.install "tars-stackchan-mcp"
        libexec.install "tars-stackchan-control"
        pkgshare.install "scripts"
        pkgshare.install "firmware"
        (bin/"tars-stackchan-mcp").write_env_script libexec/"tars-stackchan-mcp", TARS_STACKCHAN_REPO_ROOT: pkgshare
        (bin/"tars-stackchan-control").write_env_script libexec/"tars-stackchan-control", TARS_STACKCHAN_REPO_ROOT: pkgshare
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/devlikebear/tars-stackchan/releases/download/v0.2.0/tars-stackchan_0.2.0_linux_amd64.tar.gz"
      sha256 "8ba8b28fea3abd5924199d3c65f2f1be5a82c277ff454e6ac853e9b66fb3ef55"
      define_method(:install) do
        libexec.install "tars-stackchan-mcp"
        libexec.install "tars-stackchan-control"
        pkgshare.install "scripts"
        pkgshare.install "firmware"
        (bin/"tars-stackchan-mcp").write_env_script libexec/"tars-stackchan-mcp", TARS_STACKCHAN_REPO_ROOT: pkgshare
        (bin/"tars-stackchan-control").write_env_script libexec/"tars-stackchan-control", TARS_STACKCHAN_REPO_ROOT: pkgshare
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/devlikebear/tars-stackchan/releases/download/v0.2.0/tars-stackchan_0.2.0_linux_arm64.tar.gz"
      sha256 "67292b2d01d578e5b7a7ad1a5dfc6232178cd91ec34b6429912a307490a0bff1"
      define_method(:install) do
        libexec.install "tars-stackchan-mcp"
        libexec.install "tars-stackchan-control"
        pkgshare.install "scripts"
        pkgshare.install "firmware"
        (bin/"tars-stackchan-mcp").write_env_script libexec/"tars-stackchan-mcp", TARS_STACKCHAN_REPO_ROOT: pkgshare
        (bin/"tars-stackchan-control").write_env_script libexec/"tars-stackchan-control", TARS_STACKCHAN_REPO_ROOT: pkgshare
      end
    end
  end

  def caveats
    <<~EOS
      Install and connect to Claude Code:
        export TARS_STACKCHAN_TOKEN="replace-with-local-token"
        tars-stackchan-mcp install --target claude-code --firmware-tools

      The stackchan_upload_firmware tool is hidden unless TARS_STACKCHAN_ENABLE_FIRMWARE_TOOLS=1 is set.
      Run tars-stackchan-mcp doctor before allowing an agent to flash hardware.

      Start the Gemini TTS relay as a background service:
        export TARS_STACKCHAN_TOKEN="<local-token>"    # same token baked into the firmware MOD
        export GEMINI_API_KEY="<google-ai-studio-key>" # or TARS_STACKCHAN_GEMINI_API_KEY
        brew services start tars-stackchan
      The relay advertises tars-stackchan-tts.local over mDNS, so the device
      finds the current relay IP at boot without a re-flash. If mDNS does not
      resolve on your network, re-flash with TARS_STACKCHAN_TTS_HOST=<mac-ip>.
      Check it with: tars-stackchan-control tts status
    EOS
  end

  service do
    run [opt_bin/"tars-stackchan-control", "tts", "serve"]
    keep_alive true
    log_path var/"log/tars-stackchan-tts.log"
    error_log_path var/"log/tars-stackchan-tts.log"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tars-stackchan-mcp --version")
    assert_match version.to_s, shell_output("#{bin}/tars-stackchan-control --version")
    assert_match "TARS_STACKCHAN_ENABLE_FIRMWARE_TOOLS=1", shell_output("#{bin}/tars-stackchan-mcp config --target claude-code --firmware-tools")
  end
end
